project:
  type: website
  output-dir: _site
  pre-render: "yarn build"
  resources:
    - dist
  render:
    - notes/**/*.qmd
    - blog/**/*.qmd
    - index.qmd

website:
  title: "M'Sync"
  navbar:
    left:
      - text: Notes
        href: notes/index.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      - icon: moon-stars
      - href: "#"
      - aria-label: Toggle theme
  sidebar:
    style: floating
    search: true
  search:
    location: navbar
    type: overlay
    copy-button: true

format:
  html:
    theme: none
    css: [dist/main.css]
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    include-after-body:
      - _includes/scripts.html
    link-external-newwindow: true
    anchor-section: true

filters:
  - quarto

execute:
  freeze: auto
